### ISSUE TITLE
Spider Core Spawner not dropping eyes

### ISSUE THREAD

**Issue by spiderm3n** [PoleisMC/Roadmap#101]
This is similar to my previous report, so it may be a vanilla mechanic I am not sure. But I have a spider core spawner that spawns spiders and drops them to their death. A chunk hopper I have has been picking up string, but not spider eyes. Should the spiders be dropping spider eyes aswell? Is this a vanilla mechanic or something that staff made intentional?

**Comment by FireML** [comment]
Vanilla Mechanics
