### ISSUE TITLE
150 mob limit

### ISSUE THREAD

**Issue by spiderm3n** [PoleisMC/Roadmap#110]
I think it would be really nice if we had a small reminder in chat or on your screen once you hit the 150 mob killing limit for jobs and when you start getting paid for killing mobs again

**Comment by Bushpeng** [comment]
This is a rolling limit of 150 mobs killed per mob per second that expires after 5 minutes. So, enderman, zombies, skeletons, spiders, blazes, etc all have separate counters for them and update each second that passes. The first zombie you kill is tagged and expires after 5 minutes and so is every zombie you kill after that first one. Messaging players when they have reached the limit per mob over that time period will be spammy to the player when they are actively killing mobs repeatedly and frequently reach the job payout cap of 150 mobs. This is denied.
