### ISSUE TITLE
Dune Armor Trim Not Spawning(?)

### ISSUE THREAD

**Issue by spiderm3n** [PoleisMC/Roadmap#112]
Me, lastfatwookie, stroud7310, and ebb_and_flow have searched the resource world before & after the most recent reset and have not seemed to be able to find any dune armor trims. I am not sure if staff have disabled the armor trim spawning or if there is some bug in the code or some other thing. There is a 14.3% of a dune trim spawning in a desert temple chest, and we have all collectively searched through probably 30 temples, equalling 120 chests total. By using a successive odds equation of (1-.143)^120, the chance of us not finding one by now is about 0.0000009%, which is pretty much impossible. I only bring that up not to sound like a smartass but just to show that I have looked very thoroughly <:okay:1095054572789182546>

**Comment by Bushpeng** [comment]
This has been corrected.
