### ISSUE TITLE
Chunk hopper links

### ISSUE THREAD

**Issue by spiderm3n** [PoleisMC/Roadmap#128]
Would it be possible to add a way to change the order of the linked containers. At the moment there is no way to change the order of them, which is annoying when you want to add a new container that you want to have a higher priority (using "insert by order" == True) than previously added containers.

**Comment by Bushpeng** [comment]
This is already a feature

**Comment by Bushpeng** [comment]
When you are in the linked containers menu, you can hover over the containers and change the priority of the container by following the instructions within the lore.
