### ISSUE TITLE
Cluescroll

### ISSUE THREAD

**Issue by spiderm3n** [PoleisMC/Roadmap#129]
Place ....  any Wood Block is not working i tried planks,,stripped and logs in Kingdoms and resource placement

**Comment by Bushpeng** [comment]
This is not a bug. The scroll clue says to place any wood block, which is craftable with four logs in a crafting table.

![image](https://github.com/PoleisMC/Roadmap/assets/94489904/992a6b25-19c3-4523-b315-ba384a6972a6)
