### ISSUE TITLE
`/s allies` formatting error

### ISSUE THREAD

**Issue by spiderm3n** [PoleisMC/Roadmap#130]
doing `/s allies` is not formatted properly in the popup GUI

**Comment by Bushpeng** [comment]
The GUI itself is fine, but the player heads that are showing aren't the heads that should be showing.

**Comment by Bushpeng** [comment]
Additional information from the bug report is stating that the spacing and such are different. The GUIs were updated to be uniform in nature and the GUI now fits this. The report isn't a bug
