### ISSUE TITLE
"step 1..." preward

### ISSUE THREAD

**Issue by spiderm3n** [PoleisMC/Roadmap#15]
no sticks given

**Comment by spiderm3n** [comment]
This has been updated in the playtime reward config and is awaiting upload to the production server

**Comment by Bushpeng** [comment]
Also, the command used is limited to a maximum of 64 per time the command is ran either by the plugin itself - or another plugin preventing illegal stacks.

The issues within this reward have been corrected and uploaded to production (live) server.
