### ISSUE TITLE
Geodes/Ice Godes

### ISSUE THREAD

**Issue by spiderm3n** [PoleisMC/Roadmap#24]
I'de noticed that geodes are gained from breaking ice maybe add ice geodes to a thing and fix the geodes rewards as a whole theyre pretty poor as is right. I would love to hear other players opinions, right now im thinking it would be cool to have certains pets obtainable within opening a geodude like as in a 1 - 1000 chance or something and a differenet pet wth a similar chance but for an ice geodude

**Comment by Bushpeng** [comment]
Adding in ice geodes is denied due to the lack of drop tables for both types of geodes separately. All of the caches from mcMMO have been rebalanced and do feature pet caches as a reward
