### ISSUE TITLE
chunk hopper upgrade prices

### ISSUE THREAD

**Issue by spiderm3n** [PoleisMC/Roadmap#39]
1. Lower the current chunk hopper upgrade prices. To me the upgrade prices seem very high. To produce a single fully upgraded chunk hopper you need over 400k (maybe 500k?), which seems excesive. the increasing price with each upgrade should be removed and

**Comment by Bushpeng** [comment]
This suggestion was put in before the jobs were rebalanced to pay as they should this suggestion is denied as it no longer takes as long as it once did to reach the alleged 400k listed here.
