### ISSUE TITLE
Remove limitations

### ISSUE THREAD

**Issue by spiderm3n** [PoleisMC/Roadmap#40]
Currently creative has limitations/restrictions that are too strict. For instance very limited number of chests, items can't be dropped, and many more. Creative is meant to be a place where you can be creative, but in its current form it is too limiting. I would suggest changing the limitations/restrictions so that they are the same as in Towny. This would also mean that people can test something in creative knowing that it if works there then it will also work in Towny.

**Comment by FireML** [comment]
Copied from Discord:
- Mob Cap set to a much higher number (I believe this includes chests for whatever reason)
- Disabled mob eggs and Enabled all other methods of mob spawning
