### ISSUE TITLE
Set home icon togglable

### ISSUE THREAD

**Issue by spiderm3n** [PoleisMC/Roadmap#49]
When you set a home you get a gui pop up asking you to pick an icon for that home which isnt even required my suggestion would be to make this icon popup togglable so that when you set a home the gui for it stops appearing because Im finding it pretty annoying especially now that resource has been reset and im resetting all my homes.

**Comment by Bushpeng** [comment]
Setting a home icon can be completed when you set the home by completing the following command syntax:
/sethome <name> <icon>
