### ISSUE TITLE
Dyes/Architect

### ISSUE THREAD

**Issue by spiderm3n** [PoleisMC/Roadmap#50]
Add smelting cactus and other dye crafting stuff related stuff to the architect job. Just noticed you dont get architect xp from crafting green concrete powder so maybe add crafting concrete powders to the architect job too.

**Comment by Bushpeng** [comment]
Smelting and crafting dyes have been added to aristos job, but are buggy right now.
Crafting the powder is part of a job now too with the rebalance.
