### ISSUE TITLE
Treasure Chests

### ISSUE THREAD

**Issue by spiderm3n** [PoleisMC/Roadmap#62]
At the minute treasure chests as a whole seem way too good to be true especially certain items within. I've only excavated a little but nether stars, reset tokens and repair tokens seemed way too easy to obtain from them. As well if you've got /condense and keybind that now the grind to get treasure chests is so much easier too which fuels how too good to be true they are. I'd suggest testing out treasure chests more to see what seems too easy to get within them for how rare they supposed to be like nether stars and the tokens and make changes were its deemed needed and maybe even added gold ingots and diamonds to the chest which varies in amount between like 8 - 32. 🤷‍♂️  Well im off to go excavate

**Comment by Bushpeng** [comment]
Buried Treasure, Geodes, and Haleius' Catch have all been rebalanced and are on the live server
