### ISSUE TITLE
Chunkload cmd

### ISSUE THREAD

**Issue by spiderm3n** [PoleisMC/Roadmap#71]
I'm unable to do the command /chunkload on a specific chunk I've tried /chunkload remove but it says I dont have that chunk loaded. The only reason I can think of is that someone else mightve chunkloaded this chunk maybe? Idk how it works but if only one person can chunkload a specific chunk maybe make it so people cant chunkload in others claims or add a command /chunkload who so you can see whos chunkloaded that chunk :d

**Comment by FireML** [comment]
We need to improve the Denizen hook within Settlements as players who aren't in your settlement can chunkload in your claims
